# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */
# wallust template - colors-hyprland

$background = rgb(1D1E1F)
$foreground = rgb(C7D7D6)
$color0 = rgb(434546)
$color1 = rgb(15171A)
$color2 = rgb(2F1515)
$color3 = rgb(381413)
$color4 = rgb(615051)
$color5 = rgb(9A382B)
$color6 = rgb(476A68)
$color7 = rgb(A7BEBC)
$color8 = rgb(758584)
$color9 = rgb(1C1F22)
$color10 = rgb(3E1C1B)
$color11 = rgb(4B1B19)
$color12 = rgb(826B6C)
$color13 = rgb(CD4A3A)
$color14 = rgb(5F8D8A)
$color15 = rgb(A7BEBC)
