# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */
# wallust template - colors-hyprland

$background = rgb(141414)
$foreground = rgb(E2DDDD)
$color0 = rgb(3B3B3B)
$color1 = rgb(491419)
$color2 = rgb(621D26)
$color3 = rgb(961B25)
$color4 = rgb(A91D28)
$color5 = rgb(AE613E)
$color6 = rgb(817676)
$color7 = rgb(CDC6C6)
$color8 = rgb(908A8B)
$color9 = rgb(611B21)
$color10 = rgb(832733)
$color11 = rgb(C72432)
$color12 = rgb(E12636)
$color13 = rgb(E88153)
$color14 = rgb(AC9D9E)
$color15 = rgb(CDC6C6)
