# /* ---- 💫 https://github.com/JaKooLit 💫 ---- */
# wallust template - colors-hyprland

$background = rgb(250F1A)
$foreground = rgb(DCD9DA)
$color0 = rgb(AEA9AB)
$color1 = rgb(9A9C9F)
$color2 = rgb(B5634F)
$color3 = rgb(B5634F)
$color4 = rgb(6B6773)
$color5 = rgb(82554D)
$color6 = rgb(57484C)
$color7 = rgb(5C5E5F)
$color8 = rgb(8F9294)
$color9 = rgb(CDD0D4)
$color10 = rgb(D85A3A)
$color11 = rgb(D85A3A)
$color12 = rgb(7B7686)
$color13 = rgb(9B5E54)
$color14 = rgb(614C52)
$color15 = rgb(DEDFE1)
