"$schema" = 'https://starship.rs/config-schema.json'

palette = 'eyesaver'
continuation_prompt = '[ ▶▶ ](blink fg: #ff7044)'
add_newline = false


# 1. os hostname/user
# 2. directory
# 3. git
# 4. docker
# 5. shell / lvl sudo character

format = """\
[ ](color_a)\
$os\
[](fg:color_a bg:color_b)\
$directory\
[](fg:color_b bg:color_c)\
$git_branch\
$git_status\
[](fg:color_c bg:color_d)\
$docker_context\
[](color_d)\
 $shlvl$shell$nix_shell $sudo$character (bg:color_d)\
"""

right_format = """\
[](color_d)\
$time\
$direnv\
[](bg:color_d fg:color_c)\
$package\
$python\
$nodejs\
$kotlin\
$gradle\
[](bg:color_c fg:color_b)\
$cmd_duration\
[](fg:color_b)\
"""

[palettes.eyesaver]
color_a = '#553500'
color_b = '#763721'
color_c = '#a05000'
color_d = '#ffaa00'
fg_a = '#fffff0'
fg_b = '#dddd00'
fg_c = '#333333'
fg_d = '#112211'
orange = '#ffa000'

[character]
success_symbol = '[](bold orange) '
error_symbol = '[](bold red) '
#vimcmd_symbol = "[■](italic dimmed orange)"
# not supported in zsh
#vimcmd_replace_one_symbol = "◌"
#vimcmd_replace_symbol = "□"
#vimcmd_visual_symbol = "▼"
format = '$symbol'

[os]
disabled = false
style = 'bg:color_a fg:fg_a'
format = '[ $symbol ]($style)'

[hostname]
ssh_only = false
ssh_symbol = " "
style = "bg:color_a fg:fg_a"
format = "[$hostname$ssh_symbol]($style)"
disabled = false

[username]
disabled = false
show_always = true
style_user = 'bg:color_a fg:fg_a'
style_root = 'red bold'
format = "[$user@]($style)"

[directory]
style = "bg:color_b fg:fg_b"
format = "[ $path ]($style)"
truncation_length = 4
truncation_symbol = "…/"
truncate_to_repo = true
fish_style_pwd_dir_length = 1
read_only = '🔒'
read_only_style = 'red'

[git_branch]
symbol = " "
style = "bg:color_c fg:fg_c"
format = '[ $symbol $branch ]($style)'
truncation_length = 10
truncation_symbol = '…'

[git_commit]
tag_symbol = '  '

[git_status]
style = "bg:color_c fg:fg_c"
format = '[($all_status$ahead_behind )]($style)'

[docker_context]
symbol = " "
format = '[$symbol](bg:color_d fg:fg_d)'


[package]
style = "bg:color_c fg:fg_c"
format = '[$symbol($version)]($style)'


[env_var.VIMSHELL]
format = "[$env_value]($style)"
style = 'green italic'

[sudo]
format = "[$symbol]($style)"
style = "bold italic bright-purple"
symbol = "⋈┈"
disabled = false

[shell]
fish_indicator = '󰈺 '
bash_indicator = '󰊇 '
zsh_indicator = '󰍉 '
nu_indicator = '󱆃 '
powershell_indicator = ' '
unknown_indicator = '? '
style = 'orange bold'
disabled = false
format = ' [$indicator]($style)'

[shlvl]
disabled = false
format = ' $symbol$shlvl'
threshold = 2
repeat = true
style = 'orange bold'
symbol = ''

[cmd_duration]
min_time = 500
format = '[ $duration](bg:color_b fg:bold yellow)'


[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "
".worktrees" = "②"

[direnv]
format = '[$symbol$loaded/$allowed]($style)'
symbol = 'direnv'
style = 'bold orange'


[nodejs]
symbol = ""
style = "bg:color_c fg:fg_c"
format = '[ $symbol ($version) ]($style)'

[rust]
symbol = ""
style = "bg:#362721"
format = '[[ $symbol ($version) ](fg:#f09f76 bg:#362721)]($style)'

[golang]
symbol = ""
style = "bg:color_c fg:fg_c"
format = '[ $symbol ($version) ]($style)'


[time]
disabled = false
time_format = "%R"             # Hour:Minute Format
style = "bg:color_d fg:fg_d"
format = '[  $time ]($style)'


[java]
symbol = " "
style = "bg:color_c fg:fg_c"
format = '[ $symbol ($version) ]($style)'

[kotlin]
symbol = " "
style = "bg:color_c fg:fg_c"
format = '[ $symbol ]($style)'

[lua]
symbol = " "
style = "bg:color_c fg:fg_c"
format = '[ $symbol ($version) ]($style)'

[memory_usage]
symbol = "󰍛 "
style = "bg:color_c fg:fg_c"
format = '[ $symbol ($version) ]($style)'

[meson]
symbol = "󰔷 "
style = "bg:color_c fg:fg_c"
format = '[ $symbol ($version) ]($style)'

[nix_shell]
symbol = " "


[python]
symbol = " "
style = "bg:color_c fg:fg_c"
format = '[ $symbol ($version) ]($style)'

[zig]
symbol = " "
style = "bg:color_c fg:fg_c"
format = '[ $symbol ($version) ]($style)'

[gradle]
symbol = " "
style = "bg:color_c fg:fg_c"
format = '[ $symbol ($version) ]($style)'


[os.symbols]
Alpaquita = " "
Alpine = " "
AlmaLinux = " "
Amazon = " "
Android = " "
Arch = " "
Artix = " "
CentOS = " "
Debian = " "
DragonFly = " "
Emscripten = " "
EndeavourOS = " "
Fedora = " "
FreeBSD = " "
Garuda = "󰛓 "
Gentoo = " "
HardenedBSD = "󰞌 "
Illumos = "󰈸 "
Kali = " "
Linux = " "
Mabox = " "
Macos = " "
Manjaro = " "
Mariner = " "
MidnightBSD = " "
Mint = " "
NetBSD = " "
NixOS = " "
OpenBSD = "󰈺 "
openSUSE = " "
OracleLinux = "󰌷 "
Pop = " "
Raspbian = " "
Redhat = " "
RedHatEnterprise = " "
RockyLinux = " "
Redox = "󰀘 "
Solus = "󰠳 "
SUSE = " "
Ubuntu = " "
Unknown = " "
Void = " "
Windows = "󰍲 "
