# ----------------------------------------------------- 
# General workspace rules
# name: "Default"
# ----------------------------------------------------- 

workspace = 1,default:true,persistent:true, defaultName:Main, monitor:desc:Dell Inc. DELL U3225QE SERIAL,layoutopt:layout:master
workspace = 2,persistent:true, defaultName:CLI1, monitor:desc: UGD MD180UH,layout:scrolling
workspace = 3,persistent:true, defaultName:RefLeft, monitor:desc: Dell Inc. DELL S2725QC SERIAL,layout:dwindle
workspace = 4,persistent:true, defaultName:RefRight, monitor:desc: Dell Inc. DELL S2725QC SERIAL,layout:dwindle
workspace = 5,persistent:true, defaultName:CLI2,  monitor:desc:Dell Inc. DELL U3225QE SERIAL,layout:master
workspace = 6,persistent:true, defaultName:Draw, monitor:desc: UGD MD180UH,layout:scrolling
workspace = 7,persistent:true, defaultName:Music, monitor:desc: Dell Inc. DELL S2725QC SERIAL,layout:dwindle
workspace = 8,persistent:true, defaultName:8, monitor:desc: Dell Inc. DELL S2725QC SERIAL,layout:dwindle
workspace = 9,persistent:true, defaultName:Other,  monitor:desc:Dell Inc. DELL U3225QE SERIAL,layout:scrolling
workspace = 10, persistent:true, defaultName:Messaging, monitor:desc: UGD MD180UH,layout:scrolling

# workspace = 1, persistent:true,default:true, monitor:desc:Dell Inc. DELL U3225QE SERIAL,layout:master
# workspace = 2, persistent:true, monitor:desc: UGD MD180UH,layout:scrolling
# workspace = 3, persistent:true, monitor:desc: Dell Inc. DELL S2725QC SERIAL,layout:dwindle
# workspace = 4, persistent:true, monitor:desc: Dell Inc. DELL S2725QC SERIAL,layout:dwindle
# workspace = 5, persistent:true, monitor:desc:Dell Inc. DELL U3225QE SERIAL,layout:master
# workspace = 6, persistent:true, monitor:desc: UGD MD180UH,layout:scrolling
# workspace = 7, persistent:true, monitor:desc: Dell Inc. DELL S2725QC SERIAL,layout:dwindle
# workspace = 8, persistent:true, monitor:desc: Dell Inc. DELL S2725QC SERIAL,layout:dwindle
# workspace = 9, persistent:true, monitor:desc:Dell Inc. DELL U3225QE SERIAL,layout:scrolling
# workspace = 10, persistent:true, monitor:desc: UGD MD180UH,layout:scrolling

