-- General window decoration
-- name: "Default"

hl.config({
    decoration = {
        rounding = 15,
        rounding_power = 8.0,
        active_opacity = 0.95,
        inactive_opacity = 0.8,
        fullscreen_opacity = 1.0,
        dim_modal = true,
        dim_inactive = true,
        dim_strength = 0.1,
        dim_special = 0.4,
        dim_around = 0.4,
        border_part_of_window = false,
        blur = {
            enabled = true,
            size = 6,
            passes = 2,
            new_optimizations = true,
            ignore_opacity = true,
            xray = true,
            noise = 0.01,
            contrast = 1.8,
            brightness = 0.8,
            vibrancy = 0.3,
            vibrancy_darkness = 0.1,
            popups = true,
            popups_ignorealpha = 0.1,
            input_methods = true,
            input_methods_ignorealpha = 0.1,
        },
        shadow = {
            enabled = true,
            range = 20,
            render_power = 1,
            sharp = false,
            color = "0xaa60c0ff",
            color_inactive = "0x000000aa",
            offset = "0 0",
            scale = 10.0,
        },
    },
})
