[default_session]
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "dotfiles"
path = "~/dotfiles"

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Pictures"
path = "~/Pictures"
startup_command = "yazi"

[[session]]
name = "Notes"
path = "~/Documents/personal-notes/notes"

[[session]]
name = "PRs"
path = "~/Documents/personal-notes/notes"
startup_command = "gh dash"

# -------------------------------------------
# REDACTED
# -------------------------------------------
[[session]]
name = "REDACTED Notes"
path = "~/Projects/REDACTED/notes/REDACTED/"
# startup_command = "nvim $(fzf) "

[[session]]
name = "REDACTED Projects"
path = "~/Projects/REDACTED/"

[[session]]
name = "REDACTED Worktrees"
path = "~/Projects/REDACTED/worktrees"


[[session]]
name = "REDACTED PRs"
path = "~/Projects/REDACTED/notes/REDACTED/"
startup_command = "gh dash"
