[default_session]
startup_command = "nvim . -c ':Telescope find_files'"
preview_command = "eza --all --git --icons --color=always {}"

[[session]]
name = "dotfiles"
path = "~/dotfiles"

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Pictures"
path = "~/Pictures"
startup_command = "yazi"

[[session]]
name = "Notes"
path = "~/Documents/personal-notes/notes"
secret = "***REMOVED***"

