[default_session]
preview_command = "eza --all --git --icons --color=always {}"
# startup_command = "yazi"

[[session]]
name = "dotfiles"
path = "~/dotfiles"
startup_command = "yazi"

[[session]]
name = "Downloads"
path = "~/Downloads"
startup_command = "yazi"

[[session]]
name = "Pictures"
path = "~/Pictures"
startup_command = "yazi"

[[session]]
name = "Notes"
path = "~/Documents/personal-notes/notes"
# startup_command = "nvim (fzf)"

[[session]]
name = "REDACTED Notes"
path = "~/Projects/REDACTED/notes/REDACTED/"
# startup_command = "nvim $(fzf) "

[[session]]
name = "REDACTED Projects"
path = "~/Projects/REDACTED/"

[[session]]
name = "square_root"
path = "~/Projects/REDACTED/infra/square_root"
# startup_command = "nvim $(fd --type directory --max-depth 3 | fzf)"
[[session]]
name = "BigCom"
path = "~/Projects/REDACTED/payments/psq-payments-bigcom/"

