# ----------------------------------------------------- 
# Layouts
# ----------------------------------------------------- 

dwindle {
    pseudotile = true
    preserve_split = true
}

master {
    # Commented out due to compatibility reasons
    # new_status = master
}

gestures {
    # workspace_swipe = false
}

binds {
    workspace_back_and_forth = false
    allow_workspace_cycles = true
    workspace_center_on = 1
    movefocus_cycles_fullscreen = true
    movefocus_cycles_groupfirst = true

    pass_mouse_when_bound = true
}
cursor {
    sync_gsettings_theme = true
    persistent_warps = true
    warp_on_change_workspace = 1
    default_monitor = desc: Dell Inc. DELL U3225QE SERIAL
    zoom_factor = 1.0
    zoom_rigid = true
    zoom_detached_camera = false 
    enable_hyprcursor = true
    hide_on_key_press = false
    hide_on_touch = true
    hide_on_tablet = true
    warp_back_after_non_mouse_input = false
}


