
monitorv2 {
    # Main Center Monitor
    output = desc: Dell Inc. DELL U3225QE SERIAL
    # mode    = 3840x2160@120
    mode   = preferred
    position = auto
    # position = 2160x0
    scale   = 1.5
    transform = 0
}

monitorv2 {
    # XPPen
    output = desc: UGD MD180UH
    # mode    = 3840x2160@120
    mode   = preferred
    position = auto-center-down
    # position = 2160x0
    scale   = 1.5
    transform = 0
}
monitorv2 {
    # Left Vertical Monitor
    output = desc: Dell Inc. DELL S2725QC SERIAL
    # mode    = 3840x2160@60
    mode    = preferred
    # position = 0x0
    # position = -3840x0

    position = auto-center-left
    # position = auto-center-left
    scale   = 1.5
    transform = 1
}


monitorv2 {
    # Right Vertical Monitor
    output = desc: Dell Inc. DELL S2725QC SERIAL
    # mode    = 3840x2160@60
    mode    = preferred
    # position = 6000x0
    # position = 3840x0
    position = auto-center-right

    scale   = 1.5
    transform = 3
}
