
monitorv2 {
    # Left Vertical Monitor
    output = desc: Dell Inc. DELL S2725QC SERIAL
    # mode    = 3840x2160@60
    mode    = preferred
    # position = 0x0
    position = -3840x0

    # position = auto left
    scale   = 1.0
    transform = 1
}
monitorv2 {
    # Main Center Monitor
    output = desc: Dell Inc. DELL U3225QE SERIAL
    # mode    = 3840x2160@120
    mode   = preferred
    position = 0x300
    # position = 2160x0
    scale   = 1.0
    transform = 0
}
monitorv2 {
    # xppen when usbc NO DOCK
    output = desc: UGD MD180UH
    mode = preferred
    position = 0x2460
    scale = 1.0
    transform = 0
}
monitorv2 {
    # Right Vertical Monitor
    output = desc: Dell Inc. DELL S2725QC SERIAL
    # mode    = 3840x2160@60
    mode    = preferred
    # position = 6000x0
    position = 3840x0
    # position = auto right
    scale   = 1.0
    transform = 3
}
monitorv2 {
    # Built-in Laptop Monitor
    output = desc: BOE 0x0823
    # mode    = 1920x1080@60.0
    mode    = preferred
    position = 6000x720
    # position = 8163x0
    scale   = 1.0
    transform = 0
    disabled = false
}

# monitor=DP-1,3840x1080@60,0x0,1.0
# monitor=eDP-1,disable

# monitor=HDMI-A-1,highres,0x1080,1.0
# monitor=,preferred,auto,1.0
