#!/usr/bin/env sh
# Generate the luacheck field spec for `hl`, the global Hyprland injects into its
# Lua config, from the authoritative LuaLS stubs shipped by the hyprland package.
#
# The stubs are themselves autogenerated and change with every hyprland release,
# so the spec is derived rather than hand-written: a hand-written copy drifts
# silently and nobody would diff 200 fields to notice. Run this after a hyprland
# upgrade and commit the result.
#
#   mise run gen:luacheck-hl-std
#
# Output is a Lua chunk returning a table shaped for luacheck's `read_globals`,
# loaded by .luacheckrc. Only HL.API and its *Namespace classes are walked —
# everything else in the stubs describes values `hl` returns, which luacheck does
# not track through a call and so cannot check.
set -eu

STUB="${HL_STUB:-/usr/share/hypr/stubs/hl.meta.lua}"
OUT="${1:-mise-scripts/luacheck-hl-std.lua}"

if [ ! -r "$STUB" ]; then
  echo "gen-luacheck-hl-std: stub not found: $STUB" >&2
  echo "  install the hyprland package, or point HL_STUB at hl.meta.lua" >&2
  exit 1
fi

awk -v stub="$STUB" '
# ---@class HL.Something  — start collecting fields for that class.
/^---@class HL\./ {
	cls = $2
	next
}

# ---@field name <type...>  — record name and the first token of the type. A
# field whose type is one of the *Namespace classes is a nested table and gets
# recursed into; anything else (fun(...), a value class) is a leaf.
/^---@field / {
	if (cls == "") next
	name = $2
	type = $3
	if (name == "[string]") {
		open[cls] = 1        # ---@field [string] any — arbitrary keys allowed
		next
	}
	n = ++count[cls]
	fname[cls, n] = name
	ftype[cls, n] = type
	next
}

# Anything else ends the annotation block.
/^[^-]/ { cls = "" }

function emit(class, indent,    i, pad, t) {
	pad = indent
	if (open[class]) print pad "other_fields = true,"
	print pad "fields = {"
	for (i = 1; i <= count[class]; i++) {
		t = ftype[class, i]
		if (t ~ /^HL\.[A-Za-z]+Namespace$/ && count[t] > 0) {
			print pad "  " fname[class, i] " = {"
			emit(t, pad "    ")
			print pad "  },"
		} else {
			print pad "  " fname[class, i] " = {},"
		}
	}
	print pad "},"
}

END {
	if (count["HL.API"] == 0) {
		print "gen-luacheck-hl-std: no HL.API fields found in " stub > "/dev/stderr"
		exit 1
	}
	print "-- GENERATED FILE — do not edit by hand."
	print "-- Source: " stub " (hyprland package)"
	print "-- Regenerate with: mise run gen:luacheck-hl-std"
	print "--"
	print "-- luacheck field spec for `hl`, the global Hyprland injects into its Lua"
	print "-- config. Loaded by .luacheckrc; see mise-scripts/gen-luacheck-hl-std.sh."
	print "return {"
	emit("HL.API", "  ")
	print "}"
}
' "$STUB" > "$OUT.tmp"

mv "$OUT.tmp" "$OUT"
echo "gen-luacheck-hl-std: wrote $OUT from $STUB"
