-- GENERATED FILE — do not edit by hand.
-- Source: /usr/share/hypr/stubs/hl.meta.lua (hyprland package)
-- Regenerate with: mise run gen:luacheck-hl-std
--
-- luacheck field spec for `hl`, the global Hyprland injects into its Lua
-- config. Loaded by .luacheckrc; see mise-scripts/gen-luacheck-hl-std.sh.
return {
  fields = {
    animation = {},
    bind = {},
    clear_crashed_lockscreen = {},
    config = {},
    curve = {},
    define_submap = {},
    device = {},
    dispatch = {},
    env = {},
    exec_cmd = {},
    exec_scheduled_prop_refresh_immediately = {},
    gesture = {},
    get_active_monitor = {},
    get_active_special_workspace = {},
    get_active_window = {},
    get_active_workspace = {},
    get_config = {},
    get_current_submap = {},
    get_cursor_pos = {},
    get_last_window = {},
    get_last_workspace = {},
    get_layers = {},
    get_loaded_plugins = {},
    get_monitor = {},
    get_monitor_at = {},
    get_monitor_at_cursor = {},
    get_monitors = {},
    get_urgent_window = {},
    get_window = {},
    get_windows = {},
    get_workspace = {},
    get_workspace_windows = {},
    get_workspaces = {},
    is_key_down = {},
    layer_rule = {},
    monitor = {},
    on = {},
    permission = {},
    timer = {},
    unbind = {},
    version = {},
    window_rule = {},
    workspace_rule = {},
    dsp = {
      fields = {
        dpms = {},
        event = {},
        exec_cmd = {},
        exec_raw = {},
        exit = {},
        focus = {},
        force_idle = {},
        force_renderer_reload = {},
        global = {},
        layout = {},
        no_op = {},
        pass = {},
        release_input_capture = {},
        send_key_state = {},
        send_shortcut = {},
        submap = {},
        cursor = {
          fields = {
            move = {},
            move_to_corner = {},
          },
        },
        group = {
          fields = {
            active = {},
            lock = {},
            lock_active = {},
            move_window = {},
            next = {},
            prev = {},
            toggle = {},
          },
        },
        window = {
          fields = {
            alter_zorder = {},
            bring_to_top = {},
            center = {},
            clear_tags = {},
            close = {},
            cycle_next = {},
            deny_from_group = {},
            drag = {},
            float = {},
            fullscreen = {},
            fullscreen_state = {},
            kill = {},
            move = {},
            pin = {},
            pseudo = {},
            resize = {},
            set_prop = {},
            signal = {},
            swap = {},
            tag = {},
            toggle_swallow = {},
          },
        },
        workspace = {
          fields = {
            change_id = {},
            move = {},
            rename = {},
            swap_monitors = {},
            toggle_special = {},
          },
        },
      },
    },
    layout = {
      fields = {
        register = {},
      },
    },
    notification = {
      fields = {
        create = {},
        get = {},
      },
    },
    plugin = {
      other_fields = true,
      fields = {
        load = {},
      },
    },
  },
}
