preload = $HOME/Pictures/wallpapers/red-theme/red-sunset-on-the-matterhorn-mountain-peak-fnk61mulo8j5coi8.jpg
wallpaper = ,$HOME/Pictures/wallpapers/red-theme/red-sunset-on-the-matterhorn-mountain-peak-fnk61mulo8j5coi8.jpg

splash = true
