# preload = $HOME/.config/ml4w/assets/blank.png
# wallpaper = ,$HOME/.config/ml4w/assets/blank.png
preload = $HOME/wallpaper/explorer_orange_sunset.jpg
wallpaper ,$HOME/wallpaper/explorer_orange_sunset.jpg

splash = true
