preload = /home/btilford/Pictures/wallpapers/red-theme/trees-landscape-colorful-forest-sunset-night-697398-wallhere.com.jpg
wallpaper = ,$HOME/Pictures/wallpapers/red-theme/trees-landscape-colorful-forest-sunset-night-697398-wallhere.com.jpg

splash = true
