# ----------------------------------------------------- 
# Window rules
# ----------------------------------------------------- 

# Generic Floating window like browser file chooser
windowrulev2 = float, title:^(Save\sFile|Open\sFile)$, class:brave

windowrulev2 = tile,class:^(Microsoft-edge)$
windowrulev2 = tile,class:^(Brave-browser)$
windowrulev2 = tile,class:^(Chromium)$
windowrulev2 = float,class:^(pavucontrol)$
windowrulev2 = float,class:^(blueman-manager)$
windowrulev2 = float,class:^(nm-connection-editor)$
windowrulev2 = float,class:^(qalculate-gtk)$

# Browser Picture in Picture
windowrulev2 = float, title:^(Picture-in-Picture)$
windowrulev2 = pin, title:^(Picture-in-Picture)$
windowrulev2 = move 69.5% 4%, title:^(Picture-in-Picture)$

layerrule = blur, class:gtk-layer-shell
# Wlogout
windowrulev2 = float, class:^([Ww]logout)$
windowrulev2 = size, 500 500, class:^([Ww]logout)$
layerrule = blur, class:^([Ww]logout)$
windowrulev2 = float, title:^([Ww]logout)$
windowrulev2 = size, 500 500, class:^([Ww]logout)$


# Fix chrome/brave issues with context menus
windowrulev2=noblur,class:^(Brave-browser)$,title:^()$

# Yazi
windowrulev2 = float, class:(app.filemanager)
windowrulev2 = size 1000, 652, class:(app.filemanager)
windowrulev2 = stayfocused, class:(app.filemanager)
windowrulev2 = noshadow, class:(app.filemanager)
windowrulev2 = noborder, class:(app.filemanager)

# Clipboard
windowrulev2 = float, class:(app.clipse)
windowrulev2 = size 800, 652, class:(app.clipse)
windowrulev2 = stayfocused, class:(app.clipse)

windowrulev2 = noshadow, class:(app.clipse)
windowrulev2 = noborder, class:(app.clipse)

# Clipboard
windowrulev2 = float,class:(app.floatterm)
windowrulev2 = size 50%, 350, class:(app.floatterm)
windowrulev2 = stayfocused, class:(app.floatterm)
# windowrulev2 = shadow, class:(app.floatterm)
windowrulev2 = noborder, class:(app.floatterm)
windowrulev2 = move 25% 0, class:(app.floatterm)
windowrulev2 = rounding 10, class:(app.floatterm)
windowrulev2 = dimaround, class:(app.floatterm)

# Jetbrains Tollbox
windowrulev2 = float, class:jetbrains-toolbox
windowrulev2 = move 75% 100, class:jetbrains-toolbox
windowrulev2 = workspace 1, class:jetbrains-toolbox
windowrulev2 = monitor 1, class:jetbrains-toolbox
# layerrule = unset,blur, namespace:waybar
layerrule = ignorealpha 0, namespace:waybar
layerrule = xray on, namespace:waybar

