set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
# set -g @plugin 'omerxx/tmux-sessionx'
set -g @plugin 'jimeh/tmuxifier'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'catppuccin/tmux'
set -g @plugin 'aserowy/tmux.nvim'
set -g @plugin 'omerxx/tmux-floax'
set -g mouse
set -g mode-keys vi
# set -s terminal-overrides '*:Ss=\E[%p1%d q:Se=\E[2 q'
set -g allow-passthrough on
set -g detach-on-destroy off
set -g default-terminal 'tmux-256color'
set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style 'rounded'
run ~/.tmux/plugins/tmux/catppuccin.tmux




set -g history-limit 20000
set -g status-position 'top'
set -g status-bg "#222222"
set -g status-fg "#cccccc"
set -g window-status-current-style bg="#2a2a2a",fg="#bb8800"
set -g window-status-style bg="#444444"


# set -g @sessionx-bind ''
# set -g @sessionx-custom-paths '~/dotfiles/,~/Documents/personal-notes/notes'
# set -g @sessionx-custom-paths-subdirectories 'false'
# set -g @sessionx-fzf-builtin-tmux 'on'

# Keybindings
unbind r
bind r source-file ~/.tmux.conf
bind-key h select-pane -L
bind-key l select-pane -R
bind-key k select-pane -U
bind-key j select-pane -D
bind-key -T copy-mode-vi v send -X begin-selection
bind-key -T copy-mode-vi y send -X copy-selectiton-and-cancel
bind-key -T copy-mode-vi P send -X paste-buffer
bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy"
bind-key C-e run-shell "edit-output.sh"

set -g status-right-length 100
set -g status-left-length 100
# set -g status-left ""
# Right Status
set -g status-right "#{E:@catppuccin_status_application}"
set -agF status-right "#{E:@catppuccin_status_host}"
set -ag status-right "#{E:@catppuccin_status_session}"
set -ag status-right "#{E:@catppuccin_status_user}"
set -agF status-right "#{E:@catppuccin_status_directory}"

# Left Status

set -g @plugin 'aserowy/tmux.nvim'

# navigation
set -g @tmux-nvim-navigation true
set -g @tmux-nvim-navigation-cycle true
set -g @tmux-nvim-navigation-keybinding-left 'C-h'
set -g @tmux-nvim-navigation-keybinding-down 'C-j'
set -g @tmux-nvim-navigation-keybinding-up 'C-k'
set -g @tmux-nvim-navigation-keybinding-right 'C-l'

# resize
set -g @tmux-nvim-resize true
set -g @tmux-nvim-resize-step-x 1
set -g @tmux-nvim-resize-step-y 1
set -g @tmux-nvim-resize-keybinding-left 'M-h'
set -g @tmux-nvim-resize-keybinding-down 'M-j'
set -g @tmux-nvim-resize-keybinding-up 'M-k'
set -g @tmux-nvim-resize-keybinding-right 'M-l'



# run ~/.config/tmux/plugins/tmux-plugins/tmux-cpu/cpu.tmux
# run ~/.config/tmux/plugins/tmux-plugins/tmux-battery/battery.tmux
# Needs to be last line
run ~/.tmux/plugins/tpm/tpm
