return {
	{
		"nvim-treesitter/nvim-treesitter-context",
		dependencies = { "nvim-treesitter/nvim-treesitter" },
		config = function()
			require("treesitter-context").setup()
		end,
	},
	{ -- Highlight, edit, and navigate code
		"nvim-treesitter/nvim-treesitter",
		build = ":TSUpdate",
		main = "nvim-treesitter.configs", -- Sets main module to use for opts
		-- [[ Configure Treesitter ]] See `:help nvim-treesitter`
		opts = {
			ensure_installed = {
				"bash",
				"c",
				"diff",
				"html",
				"lua",
				"luadoc",
				"markdown",
				"markdown_inline",
				"query",
				"vim",
				"vimdoc",
				"sql",
				"java",
				"kotlin",
				"typescript",
				"javascript",
				"html",
				"xml",
				"css",
				"latex",
				"norg",
				"scss",
				"svelte",
				"tsx",
				"typst",
				"vue",
				"regex",
				"comment",
				"go",
				"zig",
				"awk",
				"desktop",
				"dockerfile",
				"dot",
				"editorconfig",
				"fish",
				"git_config",
				"git_rebase",
				"gitattributes",
				"gitcommit",
				"gitignore",
				"graphql",
				"gpg",
				"hcl",
				"hjson",
				"helm",
				"hocon",
				"http",
				"hyprlang",
				"javadoc",
				"jinja",
				"jinja_inline",
				"jq",
				"jsdoc",
				"json",
				"json5",
				"jsonc",
				"llvm",
				"luadoc",
				"make",
				"markdown_inline",
				"mermaid",
				"meson",
				"nginx",
				"nu",
				"passwd",
				"pem",
				"printf",
				"python",
				"regex",
				"readline",
				"requirements",
				"scss",
				"strace",
				"svelte",
				"terraform",
				"tmux",
				"toml",
				"tsv",
				"tsx",
				"vim",
				"vimdoc",
				"csv",

				-- "mermaid",
				-- "fish",
				-- "zsh",
			},
			-- Autoinstall languages that are not installed
			auto_install = true,
			highlight = {
				enable = true,
				-- Some languages depend on vim's regex highlighting system (such as Ruby) for indent rules.
				--  If you are experiencing weird indenting issues, add the language to
				--  the list of additional_vim_regex_highlighting and disabled languages for indent.
				additional_vim_regex_highlighting = { "ruby" },
			},
			indent = { enable = true, disable = { "ruby" } },
		},
		-- There are additional nvim-treesitter modules that you can use to interact
		-- with nvim-treesitter. You should go explore a few and see what interests you:
		--
		--    - Incremental selection: Included, see `:help nvim-treesitter-incremental-selection-mod`
		--    - Show your current context: https://github.com/nvim-treesitter/nvim-treesitter-context
		--    - Treesitter + textobjects: https://github.com/nvim-treesitter/nvim-treesitter-textobjects
	},
}
